model:
  class: sklearn.ensemble.RandomForestClassifier
  params: 
    n_estimators: [10, 50]
    max_depth: [2, 10]
    random_state: 42
    # param_1: value                  <-  in case of no hyperparameter optimization 
    # param_2: value
    # ....
    # ---------OR-----------------
    # param_1: [value1, value2, ...]  <-  in case of hyperparameter optimization 
    # param_2: [value1, value2, ...]  